#!/bin/bash

## Description: PWA Front ddev commands for fronted administration
## Usage: pwa-front
## Example: "ddev pwa-front setup"

case $1 in
      rebuild)
	  cd front
    yarn build
    ;;
      start)

    cd front
    NODE_EXTRA_CA_CERTS=`ls /usr/local/share/ca-certificates/mkcert_*.crt` yarn start
    ;;
      stop)

    killall -9 node
	;;
esac
