#!/usr/bin/env bash

## Description: PWA Front ddev host commands for frontend setup
## Usage: setup-pwa-front
## Example: "ddev setup-pwa-front first-time"

YELLOW='\033[1;33m'
NC='\033[0m'

bold=$(tput bold)
normal=$(tput sgr0)

case $1 in
    first-time)
  echo -e "${bold}Frontend setup:"
  if [[ ! -v NPM_TOKEN ]]; then
    echo -e "${bold}Provide NPM TOKEN in .ddev/.env \n"
    exit 1;
  fi
  if [ ! -d "front/node_modules" ]; then
      echo -e "${bold}Creating frontend app: \n"
      npx --yes nuxi init --packageManager yarn --force --install false --gitInit false -t gh:TYPO3-Headless/nuxt-typo3-starter front
      cd front
      mv .nuxt.config.ts nuxt.config.ts
      mv .env.example .env
      echo "@t3headless:registry=https://git.macopedia.pl/api/v4/packages/npm/" >> .npmrc
      echo "//git.macopedia.pl/api/v4/packages/npm/:_authToken=${NPM_TOKEN}" >> .npmrc
      echo "//git.macopedia.pl/api/v4/projects/811/packages/npm/:_authToken=${NPM_TOKEN}" >> .npmrc
      yarn
    else
      echo -e "${bold}Frontend app already exists."
  fi
	;;
    post-start-info)
  echo -e "${bold}Frontend has been rebuilt.\n\nUse ${YELLOW}ddev pwa-front start ${NC}${bold}to start frontend service and get server output in this console."
	;;
esac
